"""Polars plugin expressions, with a statically-typed namespace accessor.

In code organisation, the layering is one-directional:
`expr` (namespaces) -> the functional modules -> `datatypes`.
There should be no links the other direction.
"""

from geopolars import datatypes, geo
from geopolars.datatypes import (
    GeoLineString,
    GeoMultiLineString,
    GeoMultiPoint,
    GeoMultiPolygon,
    GeoPoint,
    GeoPolygon,
    LineStringXY,
    LineStringXYM,
    LineStringXYZ,
    LineStringXYZM,
    MultiLineStringXY,
    MultiLineStringXYM,
    MultiLineStringXYZ,
    MultiLineStringXYZM,
    MultiPointXY,
    MultiPointXYM,
    MultiPointXYZ,
    MultiPointXYZM,
    MultiPolygonXY,
    MultiPolygonXYM,
    MultiPolygonXYZ,
    MultiPolygonXYZM,
    PointXY,
    PointXYM,
    PointXYZ,
    PointXYZM,
    PolygonXY,
    PolygonXYM,
    PolygonXYZ,
    PolygonXYZM,
    Wkb,
    Wkt,
)

# Importing this registers the namespaces on pl.Expr as a side effect.
from geopolars.expr import Geometry, PluginExpr, as_plugin, col
from geopolars.io import read_parquet, scan_parquet, sink_parquet, write_parquet

__all__ = [
    "GeoLineString",
    "GeoMultiLineString",
    "GeoMultiPoint",
    "GeoMultiPolygon",
    "GeoPoint",
    "GeoPolygon",
    "Geometry",
    "LineStringXY",
    "LineStringXYM",
    "LineStringXYZ",
    "LineStringXYZM",
    "MultiLineStringXY",
    "MultiLineStringXYM",
    "MultiLineStringXYZ",
    "MultiLineStringXYZM",
    "MultiPointXY",
    "MultiPointXYM",
    "MultiPointXYZ",
    "MultiPointXYZM",
    "MultiPolygonXY",
    "MultiPolygonXYM",
    "MultiPolygonXYZ",
    "MultiPolygonXYZM",
    "PluginExpr",
    "PointXY",
    "PointXYM",
    "PointXYZ",
    "PointXYZM",
    "PolygonXY",
    "PolygonXYM",
    "PolygonXYZ",
    "PolygonXYZM",
    "Wkb",
    "Wkt",
    "as_plugin",
    "col",
    "datatypes",
    "geo",
    "read_parquet",
    "scan_parquet",
    "sink_parquet",
    "write_parquet",
]
