"""Polars plugin expressions, with a statically-typed namespace accessor.

In code organisation, the layering is one-directional:
`expr` (namespaces) -> the functional modules -> `datatypes`.
There should be no links the other direction.
"""

from geopolars import datatypes, geo
from geopolars.datatypes import (
    BoxType,
    BoxXY,
    BoxXYM,
    BoxXYZ,
    BoxXYZM,
    LineStringType,
    LineStringXY,
    LineStringXYM,
    LineStringXYZ,
    LineStringXYZM,
    MultiLineStringType,
    MultiLineStringXY,
    MultiLineStringXYM,
    MultiLineStringXYZ,
    MultiLineStringXYZM,
    MultiPointType,
    MultiPointXY,
    MultiPointXYM,
    MultiPointXYZ,
    MultiPointXYZM,
    MultiPolygonType,
    MultiPolygonXY,
    MultiPolygonXYM,
    MultiPolygonXYZ,
    MultiPolygonXYZM,
    PointType,
    PointXY,
    PointXYM,
    PointXYZ,
    PointXYZM,
    PolygonType,
    PolygonXY,
    PolygonXYM,
    PolygonXYZ,
    PolygonXYZM,
    Wkb,
    Wkt,
)

# Importing this registers the namespaces on pl.Expr as a side effect.
from geopolars.expr import PluginExpr, as_plugin, col
from geopolars.io import read_parquet, scan_parquet, sink_parquet, write_parquet

__all__ = [
    "BoxType",
    "BoxXY",
    "BoxXYM",
    "BoxXYZ",
    "BoxXYZM",
    "LineStringType",
    "LineStringXY",
    "LineStringXYM",
    "LineStringXYZ",
    "LineStringXYZM",
    "MultiLineStringType",
    "MultiLineStringXY",
    "MultiLineStringXYM",
    "MultiLineStringXYZ",
    "MultiLineStringXYZM",
    "MultiPointType",
    "MultiPointXY",
    "MultiPointXYM",
    "MultiPointXYZ",
    "MultiPointXYZM",
    "MultiPolygonType",
    "MultiPolygonXY",
    "MultiPolygonXYM",
    "MultiPolygonXYZ",
    "MultiPolygonXYZM",
    "PluginExpr",
    "PointType",
    "PointXY",
    "PointXYM",
    "PointXYZ",
    "PointXYZM",
    "PolygonType",
    "PolygonXY",
    "PolygonXYM",
    "PolygonXYZ",
    "PolygonXYZM",
    "Wkb",
    "Wkt",
    "as_plugin",
    "col",
    "datatypes",
    "geo",
    "read_parquet",
    "scan_parquet",
    "sink_parquet",
    "write_parquet",
]
